package com.gsclimbing.database.repository.statutory_inspection_report;

import com.gsclimbing.database.entity.statutory_inspection_report.StatutoryInspectionReportServiceCabin;
import org.springframework.data.repository.CrudRepository;

public interface StatutoryInspectionReportServiceCabinRepository extends CrudRepository<StatutoryInspectionReportServiceCabin, Integer>{}
