package com.gsclimbing.database.repository.statutory_inspection_report;

import com.gsclimbing.database.entity.statutory_inspection_report.StatutoryInspectionReportInspectionDescenderDevice;
import org.springframework.data.repository.CrudRepository;

public interface StatutoryInspectionReportInspectionDescenderDeviceRepository  extends CrudRepository<StatutoryInspectionReportInspectionDescenderDevice, Integer>{}
