package com.gsclimbing.database.repository.statutory_inspection_report;

import org.springframework.data.repository.CrudRepository;

import com.gsclimbing.database.entity.statutory_inspection_report.StatutoryInspectionReportInspectionDescenderDevice;

public interface StatutoryInspectionReportInspectionDescenderDeviceRepository  extends CrudRepository<StatutoryInspectionReportInspectionDescenderDevice, Integer>{

	StatutoryInspectionReportInspectionDescenderDevice findByUuid( String uuid );
	
}
