package com.gsclimbing.database.repository.statutory_inspection_report;

import com.gsclimbing.database.entity.statutory_inspection_report.StatutoryInspectionReportInspectionAnchorPoints;
import org.springframework.data.repository.CrudRepository;

public interface StatutoryInspectionReportInspectionAnchorPointsRepository extends CrudRepository<StatutoryInspectionReportInspectionAnchorPoints, Integer>{}
