package com.gsclimbing.database.repository.statutory_inspection_report;

import com.gsclimbing.database.entity.statutory_inspection_report.StatutoryInspectionReportInspectionReportLadder;
import org.springframework.data.repository.CrudRepository;

public interface StatutoryInspectionReportInspectionReportLadderRepository  extends CrudRepository<StatutoryInspectionReportInspectionReportLadder, Integer>{}
