package com.gsclimbing.database.repository.statutory_inspection_report;

import com.gsclimbing.database.entity.statutory_inspection_report.StatutoryInspectionReportInternalCrane;
import org.springframework.data.repository.CrudRepository;

public interface StatutoryInspectionReportInternalCraneRepository extends CrudRepository<StatutoryInspectionReportInternalCrane, Integer>{}
